### ISSUE TITLE
shader dictionary problem

### ISSUE THREAD

**Issue by mfiano** [lispgames/glkit#1]
So, I was finally able to save my project as a kernel-prepended binary for use on Windows, however, I discovered a bit of a pain with DEFDICT:

Currently, I am passing in a function for the SHADER-PATH argument, which gets a path relative to the project root, or core image if running as a binary. The problem I'm having is that when I send this executable to a friend, the shader path must be the same as when it was compiled. So obviously, a Linux pathname results in unfound shaders on Windows. As a work-around, I hard-coded in the path that he runs the code from.

Is it at all possible to have this evaluated at runtime, or can you offer another fix? Thanks

**Comment by rpav** [comment]
As discussed this appears to be an issue not with glkit or CL per se, but the process of dumping a binary.  For future reference of anyone reading this, the issue is that "compile-time" and "load-time" both happen _before_ the application is dumped.  This is a problem, because when using `defdict` as a top-level form, you're implicitly expecting "load-time" to happen just before "run-time".

The only real solution to this is to do something like:

``` lisp
(defun define-shaders ()
  (defdict ...))
```

And call this at runtime yourself.

**Comment by mfiano** [comment]
I can confirm this workaround is acceptable. Thanks.
